# config/packages/knp_paginator.yaml
knp_paginator:
  page_range: 5 # Nombre de pages à afficher dans la pagination
  default_options:
    page_name: page # Nom du paramètre de la page
    sort_field_name: sort # Nom du paramètre de tri
    sort_direction_name: direction # Nom du paramètre de direction de tri
    distinct: true # Utiliser DISTINCT dans les requêtes SQL
  template:
    pagination: "@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig" # Template de pagination
    sortable: "@KnpPaginator/Pagination/sortable_link.html.twig" # Template de lien triable
