security:
  # Configuration des hashers de mots de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Fournisseur d'utilisateurs pour recharger l'utilisateur depuis la session
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Configuration des firewalls
  firewalls:
    # Firewall pour le développement (accessible sans connexion)
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Firewall principal pour l'application
    main:
      user_checker: App\Security\UserChecker
      lazy: true
      provider: app_user_provider

      # Configuration de l'authentification par formulaire
      form_login:
        login_path: app_login # Route de la page de connexion
        check_path: app_login # Route de vérification des informations de connexion
        enable_csrf: true # Protection CSRF activée
        default_target_path: / # Chemin de redirection par défaut après connexion

      logout:
        path: app_logout # Route de déconnexion
        target: app_login # Redirection après déconnexion

  # Contrôle d'accès
  access_control:
    # Restreindre l'accès aux utilisateurs authentifiés pour certaines routes
    - { path: ^/post/new, roles: ROLE_USER } # Seuls les utilisateurs connectés peuvent accéder à /post/new
    # Ajoutez d'autres règles d'accès ici si nécessaire
    # - { path: ^/category, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

# Configuration spécifique pour les tests
when@test:
  security:
    password_hashers:
      # Réduction de la charge de travail pour les tests
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Valeur la plus basse pour bcrypt
        time_cost: 3 # Valeur la plus basse pour argon
        memory_cost: 10 # Valeur la plus basse pour argon
